name: Docker Releases

on:
  workflow_dispatch:
  push:
    tags:
      - "*.*.*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 构建Debian镜像
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile_debian
          platforms: linux/amd64
          push: true
          tags: | 
            wjqserver/caddy:2.8.4
            wjqserver/caddy:latest

      - name: 构建Alpine镜像
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile_alpine
          platforms: linux/amd64
          push: true
          tags: | 
            wjqserver/caddy:2.8.4-alpine
            wjqserver/caddy:alpine
