name: Docker Dev

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *' # 每天凌晨5点执行

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: 加载时间戳版本号
        run: |
          echo "VERSION=$(date +%Y%m%d)" >> $GITHUB_ENV 
          echo "${{ env.VERSION }}" 
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 构建Debian镜像
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile_debian
          platforms: linux/amd64
          push: true
          tags: | 
            wjqserver/caddy:${{ env.VERSION }}
            wjqserver/caddy:daily

      - name: 构建Alpine镜像
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile_alpine
          platforms: linux/amd64
          push: true
          tags: | 
            wjqserver/caddy:${{ env.VERSION }}-alpine
            wjqserver/caddy:daily-alpine
